language: node_js
node_js:
    - "0.10"
env:
    global:
        - DISPLAY=':99.0'
        - FIREFOX_BIN='./firefox/firefox'
        - CHROME_BIN=chrome
addons:
    hosts:
        - yt.aergia.eu
before_install:
    # Add repo with stable Chrome
    - curl -qq https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    # Mozdownload for latest official Firefox
    - sudo apt-get update -qq
    - sudo apt-get install -y python-pip
    - sudo pip install mozdownload
install:
    # Browsers
    - sudo apt-get install -y google-chrome-stable
    - mozdownload -t release -v latest
    - tar -xf *firefox*.tar.bz2
    # Grunt
    - npm install -g grunt
    - npm install -g grunt-cli
    - npm install nightwatch
    - npm install grunt-contrib-qunit
    - npm install grunt-contrib-jshint
before_script:
    - "sh -e /etc/init.d/xvfb start"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16"
    - bash test/nightwatch_dependency_check.sh
    - sudo sh -c 'python2 -m SimpleHTTPServer    80 2>&1 > /dev/null' &
    - sudo sh -c 'python2 -m SimpleHTTPServer 28080 2>&1 > /dev/null' &
script:
    - grunt nightwatch:chrome
    - grunt nightwatch:firefox
    - grunt qunit --verbose
    - grunt jshint
