language: node_js
node_js:
    - "0.10"
sudo: false
env:
    global:
        - DISPLAY=':99.0'
        - FIREFOX_BIN=firefox
        - CHROME_BIN=chromium-browser
        - PATH=./node_modules/.bin:${PATH}
    matrix:
        - NIGHTWATCH_TARGET=phantomjs
        - NIGHTWATCH_TARGET=chrome
        - NIGHTWATCH_TARGET=firefox
matrix:
    fast_finish: true
    allow_failures:
        - env: NIGHTWATCH_TARGET=chrome
        - env: NIGHTWATCH_TARGET=firefox
addons:
    firefox: "latest"
    hosts:
        - yt.127.0.0.1.xip.io
cache:
    directories:
        - $HOME/node_modules/selenium-standalone/.selenium/selenium-server
install:
    # devDependencies from package.json
    - npm install
    - grunt selenium
before_script:
    # start xvfb for non-phantomjs tests
    - test "$NIGHTWATCH_TARGET" = "phantomjs" || sh -e /etc/init.d/xvfb start
    - test "$NIGHTWATCH_TARGET" = "phantomjs" || /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x16
    - grunt httpd &
script:
    - grunt nightwatch:${NIGHTWATCH_TARGET}
    - grunt qunit --verbose
    - grunt jshint
after_failure:
    - ls -la test/
    - ls -la test/screenshots
    - bash test/upload_screenshots.sh
