language: node_js
node_js:
    - "0.10"
install:
    - npm install -g grunt
    - npm install -g grunt-cli
    - npm install nightwatch
    - npm install grunt-contrib-qunit
    - npm install grunt-contrib-jshint
before_script:
    - "export CHROME_BIN=chromium-browser"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    - bash test/nightwatch_dependency_check.sh
script:
    - grunt qunit --verbose
    - grunt nightwatch:all
    - grunt jshint
