language: node_js
before_script:
    - sudo $(which npm) install -g grunt
    - sudo $(which npm) install -g grunt-cli
    - sudo $(which npm) install grunt-contrib-qunit
    - sudo $(which npm) install grunt-contrib-jshint
script: grunt travis --verbose
