language: node_js
node_js:
    - "0.10"
sudo: false
env:
    global:
        - DISPLAY=':99.0'
        - FIREFOX_BIN='./firefox/firefox'
        - CHROME_BIN=chromium-browser
        - PATH=./node_modules/.bin:${PATH}
    matrix:
        - NIGHTWATCH_TARGET=phantomjs
        - NIGHTWATCH_TARGET=chrome
        - NIGHTWATCH_TARGET=firefox
matrix:
    fast_finish: true
    allow_failures:
        - env: NIGHTWATCH_TARGET=chrome
        - env: NIGHTWATCH_TARGET=firefox
addons:
    hosts:
        - yt.127.0.0.1.xip.io
    apt:
        packages:
            - python-pip
cache:
    directories:
        - $HOME/node_modules/selenium-standalone/.selenium/selenium-server
install:
    # devDependencies from package.json
    - npm install
    - npm run selenium-download
    - test "$NIGHTWATCH_TARGET" != "firefox" || pip install --user mozdownload
    - test "$NIGHTWATCH_TARGET" != "firefox" || $HOME/.local/bin/mozdownload -t release -v latest
    - test "$NIGHTWATCH_TARGET" != "firefox" || tar xf *firefox*.tar.*
before_script:
    - npm run httpd &
    # start xvfb for non-phantomjs tests
    - test "$NIGHTWATCH_TARGET" = "phantomjs" || sh -e /etc/init.d/xvfb start
script:
    - grunt qunit --verbose
    - grunt nightwatch:${NIGHTWATCH_TARGET}
    - grunt jshint
after_failure:
    - ls -la test/
    - ls -la test/screenshots
    - bash test/upload_screenshots.sh
